# Generated by Django 4.0.3 on 2022-04-08 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_opportunity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
