# Generated by Django 4.0.3 on 2022-04-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_opportunity_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='detail',
            new_name='details',
        ),
    ]
