# Generated by Django 3.2 on 2022-03-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Beneficiaries',
            new_name='beneficiaries',
        ),
    ]
