# Generated by Django 3.2 on 2022-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_rename_beneficiaries_project_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
