# Generated by Django 3.2 on 2022-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.FileField(default='brief.png', upload_to='project_image'),
        ),
    ]
