# Generated by Django 4.0.4 on 2022-05-23 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0008_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
