# Generated by Django 4.0.4 on 2022-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0012_alter_project_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation',
            field=models.IntegerField(default=0),
        ),
    ]
