# Generated by Django 4.0.4 on 2022-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0014_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
