# Generated by Django 4.0.4 on 2022-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0015_donation_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(max_length=255),
        ),
    ]
