# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0016_alter_donation_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='word',
            field=models.TextField(null=True),
        ),
    ]
