# Generated by Django 4.0.4 on 2022-06-07 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0022_alter_donation_donated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 14, 54, 38, 664801)),
        ),
        migrations.AlterField(
            model_name='word_of_support',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 14, 54, 38, 665257)),
        ),
    ]
