# Generated by Django 4.1.2 on 2022-10-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0028_alter_donation_donated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 17, 6, 127977)),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word_of_support',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 17, 6, 128976)),
        ),
    ]
