# Generated by Django 4.0.3 on 2022-04-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('sme', 'sme'), ('donor', 'donor')], max_length=100, null=True),
        ),
    ]
