# Generated by Django 4.0.4 on 2022-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_profile_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
